# Note that we recommend using https://github.com/kactlabs/censura-pre-commit-mirror instead
# This will work about 2x as fast as using the hooks in this repository
- id: censura
  name: censura
  description: "Censura: Black++ - The enhanced Python code formatter"
  entry: censura
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]
- id: censura-jupyter
  name: censura-jupyter
  description:
    "Censura: Black++ - The enhanced Python code formatter (with Jupyter Notebook support)"
  entry: censura
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi, jupyter]
  additional_dependencies: [".[jupyter]"]
